version: "3.6"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ts-express
    container_name: ts-express
    ports:
      - "9001:9001"
    volumes:
      - .:/workspace
